### ISSUE TITLE
The file mathplot\samples\sample1\mp1.cpp has mixed indent characters

### ISSUE THREAD

**Issue by asmwarrior** [naiche/wxMathPlot#1]
In some place, it use 4 white spaces, while in other lines, it use a TAB char.

I suggest we should use the 4 white spaces for all the files, at least, it should be consistent in a file.

**Comment by asmwarrior** [comment]
Also, this file contains some trailing spaces.

**Comment by naiche** [comment]
I'll try to fix that, but I prefer tabs instead of spaces.
