### ISSUE TITLE
some compiler warning about integer division

### ISSUE THREAD

**Issue by asmwarrior** [naiche/wxMathPlot#4]
Hi, I see some waning reported by the clangd LSP

For example, in mathplot.cpp, there is a line:

~~~~
            if (m_winX != 1) m_dim.x = (int) floor((double)(m_dim.x*scrx/m_winX));
~~~~

The `m_dim.x*scrx/m_winX` expression, those three variables are all integer type, so the divide may result a 0, The correct way may first convert the first one to `double`.

There are many other places about this kind of warning.

**Comment by naiche** [comment]
Hi asmwarrior, I didn't write this code and my compiler is not returning any warning, in this case, what is your sugestion, something like this?
        (int) floor(((double)m_dim.x*scrx/(double)m_winX));
Also, in this specific instance, the result of the divide being 0 wouldn't be a problem since floor() of something between 0 and 1 is also 0.

**Comment by asmwarrior** [comment]
> Hi asmwarrior, I didn't write this code and my compiler is not returning any warning, in this case, what is your suggestion, something like this? (int) floor(((double)m_dim.x*scrx/(double)m_winX)); 

Yes.
~~~~
(int) floor(((double)m_dim.x*scrx/m_winX)); 
~~~~
This should be enough, only one cast in the `numerator `.

> Also, in this specific instance, the result of the divide being 0 wouldn't be a problem since floor() of something between 0 and 1 is also 0.
I guess first convert to double is the correct fix. Also, the floor() function can do the conversion to int again.

**Comment by naiche** [comment]
> Yes.
> 
> ```
> (int) floor(((double)m_dim.x*scrx/m_winX)); 
> ```
> 
> This should be enough, only one cast in the `numerator

Ok, I'll apply it where I find this code.

**Comment by naiche** [comment]
Done, tell me if you still find any of those warnings.
