### ISSUE TITLE
running sample4 on Windows, the window get continuously refreshed when mouse moves

### ISSUE THREAD

**Issue by asmwarrior** [naiche/wxMathPlot#6]
I'm using the latest revision: [Implemented requested feature (Layers to be tracked can be defined in…](https://github.com/naiche/wxMathPlot/commit/cfe7f590e87680529347fbaeebb505a21aabf3d7)

And I see the window refreshes when the mouse moves.

See the gif screen shot.

![refresh_window_mouse_move](https://user-images.githubusercontent.com/561818/197119649-4428947a-c6e7-4f0a-b0c5-ed932aef508f.gif)

**Comment by naiche** [comment]
Should be fixed now, tell if it isn't.

**Comment by asmwarrior** [comment]
I can confirm the fix, thanks!
